backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\ActionModelInterface;
use common\models\Apple;
use common\models\AppleEatForm;
use common\models\AppleSearch;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    const APPLE_COUNT_MIN = 7;
    const APPLE_COUNT_MAX = 21;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'crop', 'falldown', 'eat', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new AppleSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', ['dataProvider' => $dataProvider]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * New crop action
     */
    public function actionCrop()
    {
        // Delete old apples
        $appleModels = Apple::find()->all();
        foreach($appleModels as $appleModel) $appleModel->delete();

        // Get number of new apples
        $appleCount = rand(self::APPLE_COUNT_MIN, self::APPLE_COUNT_MAX);

        // Create new apples
        for($i = 0; $i < $appleCount; $i++)
        {
            $newApple = new Apple();
            $newApple->save();
        }

        // Create information message
        $this->createFlash('Уродилось яблок: ' . $appleCount);

        // Return to apple list
        return $this->redirect(['index']);
    }

    /**
     * Apple fall down action
     *
     * @param integer $id
     */
    public function actionFalldown($id)
    {
        $appleModel = $this->getModel($id, 'falldown');

        if($appleModel) $appleModel->fallToGround();

        return $this->redirect(['index']);
    }

    /**
     * Apple eat action
     *
     * @param integer $id
     */
    public function actionEat($id)
    {
        $appleModel = $this->getModel($id, 'eat');

        if($appleModel)
        {
            $appleEatModel = new AppleEatForm($appleModel);
            if($appleEatModel->load(Yii::$app->request->post()) && $appleEatModel->validate() && $appleModel->eat($appleEatModel->eat))
            {
                if($appleModel->size > 0)
                    $this->createFlash('Поели яблока! Осталось: ' . ($appleModel->size * 100) . ' %', 'success');
                else
                    $this->createFlash('Съели всё яблоко!', 'warning');
            }
            else
            {
                return $this->render('eat', [
                    'title' => 'Едим яблоко',
                    'model' => $appleEatModel,
                    'left'  => intval($appleModel->size * 100),
                ]);
            }
        }

        return $this->redirect(['index']);
    }

    /**
     * Apple delete action
     *
     * @param integer $id
     */
    public function actionDelete($id)
    {
        $appleModel = $this->getModel($id, 'delete');

        if($appleModel)
        {
            $appleModel->delete();
            $this->createFlash('Яблоко удалено!', 'warning');
        }

        return $this->redirect(['index']);
    }

    /**
     * Returns apple model and checks rights for an action
     *
     * @param integer $id
     * @param string  $actionName
     * @return Apple or false
     */
    protected function getModel($id, $actionName)
    {
        $appleModel = Apple::findOne(intval($id));
        if(!$appleModel)
        {
            $this->createFlash('Яблоко не найдено на дереве! ID: ' . $id, 'error');
            return false;
        }

        if($appleModel instanceof ActionModelInterface && !$appleModel->actionAllowed($actionName))
        {
            $this->createFlash('Неразрешённое дейстие для яблока! Action: ' . $actionName, 'error');
            return false;
        }

        return $appleModel;
    }

    /**
     * Saves flash messag
     * @param string $message
     * @param string $type
     *
     * Available types: error, danger, success, info, warning
     */
    protected function createFlash($message, $type = 'success')
    {
        $session = Yii::$app->session;
        $session->addFlash($type, $message);
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/eat.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $title string */
/* @var $this yii\web\View */
/* @var $model common\models\AppleEatForm */

$this->title = $title;
$this->params['breadcrumbs'][] = 'Яблоки';
$this->params['breadcrumbs'][] = $title;
?>


<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'eat')->textInput(['maxlength' => true, 'type' => 'number']) ?>
<p>Доступно <?= $left ?> % яблока.</p>

<div class="form-group">
    <?= Html::submitButton('Есть', ['class' => 'btn btn-success']) ?>
    <?php echo Html::a('Передумать', ['index'], ['class' => 'btn btn-warning']) ?>
</div>

<?php ActiveForm::end(); ?>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Apple Application';

$this->params['breadcrumbs'][] = 'Яблоки';
?>
<div class="site-index">

    <div class="body-content">
        <p><a href="<?= \yii\helpers\Url::to(['site/crop']) ?>" class="btn btn-primary">Новый урожай <span class="glyphicon glyphicon-refresh"></span></a></p>

        <?= \yii\grid\GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                ['class' => 'common\grid\AppleColorColumn', 'attribute' => 'color'],
                'size',
                ['class' => 'common\grid\AppleStatusColumn', 'attribute' => 'status'],
                ['class' => 'yii\grid\DataColumn', 'attribute' => 'created_at', 'format' => 'dateTime'],
                ['class' => 'yii\grid\DataColumn', 'attribute' => 'falleddown_at', 'format' => 'dateTime'],
                [
                    'class' => 'common\grid\ActionColumn',
                    'defaultClass' => 'btn btn-primary btn-sm',
                    'defaultShowTitle' => false,
                    'buttons' => [
                        'falldown' => ['icon' => 'glyphicon glyphicon-arrow-down', 'title' => 'Упасть', 'class' => 'btn btn-success btn-sm'],
                        'eat'      => ['icon' => 'glyphicon glyphicon-apple', 'title' => 'Съесть'],
                        'sep'      => [],
                        'delete'   => ['icon' => 'glyphicon glyphicon-trash', 'title' => 'Удалить', 'class' => 'btn btn-danger btn-sm', 'confirm' => 'Удаляем яблоко?', 'isPost' => true],
                    ],
                ],
            ],
        ]); ?>

    </div>
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>